### ISSUE TITLE
Android?

### ISSUE THREAD

**Issue by thijsi123** [androidWG/Discord.fm#26]
So I was wondering if you could achieve a way to use this on Android with 
( I use kizzy to send my media to discord but whenever I lose my internet connection for only a millisecond, kizzy won't send anything to discord anymore. That means that I have to reactivate the service everytime)

scrobal: https://play.google.com/store/apps/details?id=com.peterjosling.scroball
And
Kizzy/android rich presence: 
https://github.com/dead8309/Kizzy
https://github.com/dead8309/KizzyRPC

**Comment by androidWG** [comment]
I've thought about doing an Android version, but as far as I knew RPC was only possible on desktop. The method that Kizzy uses with a Gateway is completely new to me!

This is interesting, and I've been looking on what kind of stack could be used. I don't want to lock myself on creating a lot of specific Android code in case we get a good opportunity to make an iOS version in the future. The project is already made in Python which is platform-agnostic, but not typically used in mobile app dev, so options are limited.

It seems like the best way is Kivy which will already solve the problem of one-codebase UI as well. Though I do think it might be better to write native apps instead since the bulk of this app is the background service, the API for which on Android is not implemented on Python directly (I assume close to the same for iOS).

Overall, I was already thinking of maybe rewriting this project in another language non-scripting language that would solve some very Python-specific problems with packaging the app on desktop and definitely help with porting to mobile. But as it stands, an Android version should probably be it's own project.

**Comment by thijsi123** [comment]
That's great to hear! ^ ^
I'm glad that this made a few more opportunities/options available for mobile rpc.

**Comment by androidWG** [comment]
Closing since the discussion seems to have run its course.
For now, I'm trying to polish my mediocre code and hopefully, eventually get a 1.0 release to look into this Android version, since that'd most likely be a whole different project with much new code. It is still **definitely** in my plans though.

@thijsi123 thank you for letting me know about this!
