### ISSUE TITLE
Rich presence on discord shows no image at all

### ISSUE THREAD

**Issue by hotshotp** [androidWG/Discord.fm#31]
![image](https://user-images.githubusercontent.com/70779662/223923995-6e6fed1b-d313-4167-a5b4-f08857c9177b.png)

When using this plugin, everything syncs except the image for the song/album never shows up, no matter which song or service I use, and it shows on LastFM. I am using windows 10 Version 21H2 build 19044.2604 and I am happy to provide any more information that is needed :)

**Comment by androidWG** [comment]
Heya! Could you please attach all your log files here?
For this specific song, I [looked it up on Last.fm](https://www.last.fm/music/7clouds/_/Jason+Derulo+-+Swalla+(Lyrics)+feat.+Nicki+Minaj+&+Ty+Dolla+$ign) and it doesn't have an image attached so Discord.fm cannot do anything about it. But since you said no tracks show a cover, I want to check your logs to see if something is up.

How to upload your log files:

1. Right-click the Discord.fm tray icon and click "Open Settings"
2. Click the "Open logs folder" button
3. When the file explorer window opens, select all the files in the folder by pressing Ctrl + A
4. Right click any of the files
5. Under the "Send to" menu, click on "Compressed (zipped) folder"
6. A new file will be created and a name will be prompted. Name it "logs" (or whatever descriptive name you'd like).
7. Drag and drop it on the comment area to upload it.

**Comment by androidWG** [comment]
Haven't found this issue myself and not enough info posted. Closing for now.
